In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [10]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [21]:
x = np.array([[1,1]]).reshape(-1,1)
x.shape

(2, 1)

In [22]:
arch = {1:2, 2:3}
#Layer 1: 2 neurons
l1_weights = np.array([[3.9545,-7.1604],
                       [3.9158, 6.9559]])

b1 = np.array([-4.1350,  0.1174]).reshape(-1,1)
net1 = l1_weights@x + b1
y1 = sigmoid(net1)
print("Net 1\n",net1)
print("y1\n",y1)


#Layer 2: 3 neurons
l2_weights = np.array([[-3.6290, -3.4968],
        [-3.6451, -2.9462],
        [ 4.0213,  3.1682]])

b2 = np.array([ 3.0724,  2.7463, -3.1982]).reshape(-1,1)
net2 = l2_weights@y1 + b2
y2 = sigmoid(net2)
print("Net 2\n",net2)
print("y2\n",y2)

#Output layer
lout_weights = np.array([[-3.3871, -3.7787,  4.1240]])
bout = np.array([1.0099])
netout = lout_weights@y2 + bout
yout = sigmoid(netout)
print("Net 2out\n",netout)
print("y2out\n",yout)

Net 1
 [[-7.3409]
 [10.9891]]
y1
 [[6.48046402e-04]
 [9.99983116e-01]]
Net 2
 [[-0.42669272]
 [-0.20221245]
 [-0.0274475 ]]
y2
 [[0.39491636]
 [0.44961845]
 [0.49313855]]
Net 2out
 [[0.00700899]]
y2out
 [[0.50175224]]
